### ISSUE TITLE
Repository Update Issues?

### ISSUE THREAD

**Issue by CodingBlueBird** [westerndigitalcorporation/RISC-V-Linux#2]
Hello,

I stumbled on your Risc-v fedora instructions and wanted to reproduce the demo.
Some instructions on the page say:
cd <freedom-u-sdk path>/riscv-pk
git remote add -f fedora-wdc-riscv <local RISC-V-Linux repo path>
git checkout 9d561e92ea39deee0f238787ba89af99dd8073ef

The line "git checkout" returns an error:
fatal: reference is not a tree: 9d561e92ea39deee0f238787ba89af99dd8073ef

Is there a missing instruction between remote add and checkout or was the sub-modules relating to this code not pushed?

Any hints would be greatly appreciated!

**Comment by atishp04** [comment]
You should provide absolute  path for fedora-wdc-riscv repo. That should work for you.

**Comment by CodingBlueBird** [comment]
I realized the message edited the commands I typed.
Here is what I typed in:

git remote add -f fedora-wdc-riscv /buildsources/SiFive/freedom-u-sdk/riscv-pk
git checkout 9d561e92ea39deee0f238787ba89af99dd8073ef 

Would providing an absolute path when I checkout my code fix the error?
git checkout 9d561e92ea39deee0f238787ba89af99dd8073ef  /buildsources/SiFive/freedom-u-sdk/riscv-pk

**Comment by atishp04** [comment]
remote repository should be <RISC-V-Linux repo> (This repository ) not riscv-pk.
9d561e9 is a commit id in this repo not in riscv-pk.

Here is an example:

:~/workspace$ git clone https://github.com/westerndigitalcorporation/RISC-V-Linux.git
Cloning into 'RISC-V-Linux'...
remote: Enumerating objects: 6240580, done.
remote: Total 6240580 (delta 0), reused 0 (delta 0), pack-reused 6240580
Receiving objects: 100% (6240580/6240580), 1.43 GiB | 32.63 MiB/s, done.
Resolving deltas: 100% (5178475/5178475), done.
Checking connectivity... done.
Checking out files: 100% (61992/61992), done.
:~/workspace$ cd riscv-pk/
:~/workspace/riscv-pk$ git remote add -f fedora-wdc-riscv ../RISC-V-Linux/
Updating fedora-wdc-riscv
remote: Counting objects: 6237690, done.
remote: Compressing objects: 100% (1017005/1017005), done.
Receiving objects: 100% (6237690/6237690), 1.43 GiB | 36.09 MiB/s, done.
remote: Total 6237690 (delta 5176466), reused 6237672 (delta 5176459)
Resolving deltas: 100% (5176466/5176466), completed with 1 local objects.
From ../RISC-V-Linux
 * [new branch]        master     -> fedora-wdc-riscv/master
:~/workspace/riscv-pk$ git checkout 9d561e9
Note: checking out '9d561e9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9d561e92... Add microsemi pcie entry in bbl.

**Comment by CodingBlueBird** [comment]
Thank you for your help!
